Repository ucsb-cs156-s23/proj-happycows-s23-6pm-2, pull requests merged in 2023-06, with the labels that each got.

#15 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#16 Change profile commons cards to display wealth and cows and compartmentalize commons card
  frontend/src/main/components/Commons/CommonsCardBox.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/stories/components/Commons/CommonsCardBox.stories.js
  frontend/src/tests/components/Commons/CommonsCardBox.test.js
  frontend/src/tests/pages/ProfilePage.test.js
Labels: 10

#21 Update cow health display to be a healthbar
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/stories/components/Commons/FarmStats.stories.js
  frontend/src/stories/components/Commons/FarmStats.stories.mdx
  frontend/src/tests/components/Commons/FarmStats.test.js
Labels: 10

#13 Buy Multiple cows
  .gitignore
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Commons/ManageCows.stories.mdx
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 20

#29 Fix image corruption on localhost
  src/main/java/edu/ucsb/cs156/happiercows/controllers/FrontendProxyController.java
Labels: pending staff review

#19 Remove unnecessary state and effect from HomePage
  frontend/src/main/pages/HomePage.js
Labels: 10

#23 Added milk price to player's profits section
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/stories/components/Commons/Profits.stories.mdx
  frontend/src/tests/components/Commons/Profits.test.js
Labels: 5

#35 Show last online time for users
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/utils/dateUtils.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/utils/dateUtils.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/testconfig/MockCurrentUserServiceImpl.java
Labels: pending staff review
